// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains definition of message ids enumeration.

#pragma once

#include <cstdint>
#include "adas/Version.h"

namespace adas
{
/// @brief Message ids enumeration.
enum MsgId : std::uint8_t
{
    MsgId_M1 = 1, ///< message id of @b M1 message. 

    // --- Extra values generated for convenience ---
    MsgId_FirstValue = 1, ///< First defined value.
    MsgId_LastValue = 1, ///< Last defined value.
    MsgId_ValuesLimit = 2, ///< Upper limit for defined values.
};

} // namespace adas
