// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains protocol version definition.

#pragma once

#include "comms/version.h"

/// @brief Version of the protocol specification.
#define ADAS_SPEC_VERSION (0U)

namespace adas
{

/// @brief Version of the protocol specification.
inline constexpr unsigned specVersion()
{
    return ADAS_SPEC_VERSION;
}

} // namespace adas

// Generated compile time check for minimal supported version of the COMMS library
static_assert(COMMS_MAKE_VERSION(5, 2, 3) <= comms::version(),
    "The version of COMMS library is too old");
