// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref adas::field::I1 field.

#pragma once

#include <cstdint>

namespace adas
{

namespace field
{

/// @brief Common types and functions for
///     @ref adas::field::I1 field.
struct I1Common
{
    /// @brief Re-definition of the value type used by
    ///     adas::field::I1 field.
    using ValueType = std::uint32_t;

    /// @brief Name of the @ref adas::field::I1 field.
    static const char* name()
    {
        return "I1";
    }

    /// @brief Compile time detection of special values presence.
    static constexpr bool hasSpecials()
    {
        return false;
    }
};

} // namespace field

} // namespace adas
