// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref adas::field::I2 field.

#pragma once

#include <cstdint>

namespace adas
{

namespace field
{

/// @brief Scope for all the common definitions of the member fields of
///     @ref adas::field::I2 field.
struct I2MembersCommon
{
    /// @brief Common types and functions for
    ///     @ref adas::field::I2Members::Element field.
    struct ElementCommon
    {
        /// @brief Re-definition of the value type used by
        ///     adas::field::I2Members::Element field.
        using ValueType = std::uint32_t;

        /// @brief Name of the @ref adas::field::I2Members::Element field.
        static const char* name()
        {
            return "Element";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };
};

/// @brief Common types and functions for
///     @ref adas::field::I2 field.
struct I2Common
{
    /// @brief Name of the @ref adas::field::I2 field.
    static const char* name()
    {
        return "I2";
    }
};

} // namespace field

} // namespace adas
