// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains definition of <b>"I4"</b> field.

#pragma once

#include <cstdint>
#include "adas/field/FieldBase.h"
#include "adas/field/I4Common.h"
#include "adas/options/DefaultOptions.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"

namespace adas
{

namespace field
{

/// @brief Definition of <b>"I4"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = adas::options::DefaultOptions, typename... TExtraOpts>
class I4 : public
    comms::field::IntValue<
        adas::field::FieldBase<>,
        std::uint32_t,
        TExtraOpts...
    >
{
    using Base =
        comms::field::IntValue<
            adas::field::FieldBase<>,
            std::uint32_t,
            TExtraOpts...
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;

    /// @brief Compile time detection of special values presence.
    static constexpr bool hasSpecials()
    {
        return adas::field::I4Common::hasSpecials();
    }

    /// @brief Name of the field.
    static const char* name()
    {
        return adas::field::I4Common::name();
    }
};

} // namespace field

} // namespace adas
