// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains definition of <b>"MsgId"</b> field.

#pragma once

#include "adas/field/FieldBase.h"
#include "adas/field/MsgIdCommon.h"
#include "adas/options/DefaultOptions.h"
#include "comms/field/EnumValue.h"
#include "comms/options.h"

namespace adas
{

namespace field
{

/// @brief Definition of <b>"MsgId"</b> field.
/// @see @ref adas::MsgId
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = adas::options::DefaultOptions, typename... TExtraOpts>
class MsgId : public
    comms::field::EnumValue<
        adas::field::FieldBase<>,
        adas::field::MsgIdCommon::ValueType,
        TExtraOpts...,
        comms::option::def::ValidNumValue<1>
    >
{
    using Base =
        comms::field::EnumValue<
            adas::field::FieldBase<>,
            adas::field::MsgIdCommon::ValueType,
            TExtraOpts...,
            comms::option::def::ValidNumValue<1>
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;

    /// @brief Single value name info entry.
    using ValueNameInfo = adas::field::MsgIdCommon::ValueNameInfo;

    /// @brief Type returned from @ref valueNamesMap() member function.
    /// @see @ref adas::field::MsgIdCommon::ValueNamesMapInfo.
    using ValueNamesMapInfo = adas::field::MsgIdCommon::ValueNamesMapInfo;

    /// @brief Retrieve name of the enum value.
    /// @see @ref adas::field::MsgIdCommon::valueName().
    static const char* valueName(ValueType val)
    {
        return adas::field::MsgIdCommon::valueName(val);
    }

    /// @brief Retrieve name of the enum value.
    /// @see @ref adas::field::MsgIdCommon::valueName().
    static const char* valueNameOf(ValueType val)
    {
        return adas::field::MsgIdCommon::valueName(val);
    }

    /// @brief Retrieve name of the @b current value
    const char* valueName() const
    {
        return valueName(Base::getValue());
    }

    /// @brief Retrieve map of enum value names.
    /// @see @ref adas::field::MsgIdCommon::valueNamesMap().
    static ValueNamesMapInfo valueNamesMap()
    {
        return adas::field::MsgIdCommon::valueNamesMap();
    }

    /// @brief Name of the field.
    static const char* name()
    {
        return adas::field::MsgIdCommon::name();
    }
};

} // namespace field

} // namespace adas
