// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains definition of protocol client default options.

#pragma once

#include "adas/options/DefaultOptions.h"

namespace adas
{

namespace options
{

/// @brief Default client options of the protocol.
template <typename TBase = adas::options::DefaultOptions>
struct ClientDefaultOptionsT : public TBase
{
};

/// @brief Alias to @ref ClientDefaultOptionsT with default template parameter.
using ClientDefaultOptions = ClientDefaultOptionsT<>;

} // namespace options

} // namespace adas
