// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains definition of protocol default options.

#pragma once

#include "comms/options.h"

namespace adas
{

namespace options
{

/// @brief Empty class to serve as the base for options.
struct EmptyOptions {};

/// @brief Default (empty) options of the protocol.
template <typename TBase = EmptyOptions>
struct DefaultOptionsT : public TBase
{
    /// @brief Extra options for fields.
    struct field
    {
        /// @brief Extra options for @ref
        ///     adas::field::I2 field.
        using I2 = comms::option::EmptyOption;
    }; // struct field

    /// @brief Extra options for messages.
    struct message
    {
        /// @brief Extra options for fields of
        ///     @ref adas::message::Msg1 message.
        struct Msg1Fields
        {
            /// @brief Extra options for @ref
            ///     adas::message::Msg1Fields::F2 field.
            using F2 = comms::option::EmptyOption;
        };
    }; // struct message

    /// @brief Extra options for frames.
    struct frame
    {
        /// @brief Extra options for layers of
        ///     @ref adas::frame::Frame frame.
        struct FrameLayers
        {
            /// @brief Extra options for @ref
            ///     adas::frame::FrameLayers::Data layer.
            using Data = comms::option::EmptyOption;

            /// @brief Extra options for @ref
            ///     adas::frame::FrameLayers::ID layer.
            using ID = comms::option::EmptyOption;
        }; // struct FrameLayers
    }; // struct frame
};

/// @brief Default (empty) options of the protocol.
using DefaultOptions = DefaultOptionsT<>;

} // namespace options

} // namespace adas
