// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains definition of protocol server default options.

#pragma once

#include "adas/options/DefaultOptions.h"

namespace adas
{

namespace options
{

/// @brief Default server options of the protocol.
template <typename TBase = adas::options::DefaultOptions>
struct ServerDefaultOptionsT : public TBase
{
};

/// @brief Alias to @ref ServerDefaultOptionsT with default template parameter.
using ServerDefaultOptions = ServerDefaultOptionsT<>;

} // namespace options

} // namespace adas
