// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains definition of <b>"Message 1"</b> message and its fields.

#pragma once

#include <tuple>
#include "adas/MsgId.h"
#include "adas/field/FieldBase.h"
#include "adas/field/I0.h"
#include "adas/field/I1.h"
#include "adas/field/I2.h"
#include "adas/field/I3.h"
#include "adas/field/I4.h"
#include "adas/message/Msg1Common.h"
#include "adas/options/DefaultOptions.h"
#include "comms/MessageBase.h"
#include "comms/options.h"

namespace adas
{

namespace message
{

/// @brief Fields of @ref Msg1.
/// @tparam TOpt Extra options
/// @see @ref Msg1
/// @headerfile adas/message/Msg1.h
template <typename TOpt = adas::options::DefaultOptions>
struct Msg1Fields
{
    /// @brief Definition of <b>"F0"</b> field.
    class F0 : public
        adas::field::I0<
            TOpt
        >
    {
        using Base =
            adas::field::I0<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return adas::message::Msg1FieldsCommon::F0Common::name();
        }
    };

    /// @brief Definition of <b>"F1"</b> field.
    class F1 : public
        adas::field::I1<
            TOpt
        >
    {
        using Base =
            adas::field::I1<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return adas::message::Msg1FieldsCommon::F1Common::name();
        }
    };

    /// @brief Definition of <b>"F2"</b> field.
    class F2 : public
        adas::field::I2<
            TOpt,
            typename TOpt::message::Msg1Fields::F2
        >
    {
        using Base =
            adas::field::I2<
                TOpt,
                typename TOpt::message::Msg1Fields::F2
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return adas::message::Msg1FieldsCommon::F2Common::name();
        }
    };

    /// @brief Definition of <b>"F3"</b> field.
    class F3 : public
        adas::field::I3<
            TOpt
        >
    {
        using Base =
            adas::field::I3<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return adas::message::Msg1FieldsCommon::F3Common::name();
        }
    };

    /// @brief Definition of <b>"F4"</b> field.
    class F4 : public
        adas::field::I4<
            TOpt
        >
    {
        using Base =
            adas::field::I4<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return adas::message::Msg1FieldsCommon::F4Common::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        F0,
        F1,
        F2,
        F3,
        F4
    >;
};

/// @brief Definition of <b>"Message 1"</b> message class.
/// @details
///     See @ref Msg1Fields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile adas/message/Msg1.h
template <typename TMsgBase, typename TOpt = adas::options::DefaultOptions>
class Msg1 : public
    comms::MessageBase<
        TMsgBase,
        comms::option::def::StaticNumIdImpl<adas::MsgId_M1>,
        comms::option::def::FieldsImpl<typename Msg1Fields<TOpt>::All>,
        comms::option::def::MsgType<Msg1<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            comms::option::def::StaticNumIdImpl<adas::MsgId_M1>,
            comms::option::def::FieldsImpl<typename Msg1Fields<TOpt>::All>,
            comms::option::def::MsgType<Msg1<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b FieldIdx_f0 index, @b Field_f0 type and @b field_f0() access fuction
    ///         for @ref Msg1Fields::F0 field.
    ///     @li @b FieldIdx_f1 index, @b Field_f1 type and @b field_f1() access fuction
    ///         for @ref Msg1Fields::F1 field.
    ///     @li @b FieldIdx_f2 index, @b Field_f2 type and @b field_f2() access fuction
    ///         for @ref Msg1Fields::F2 field.
    ///     @li @b FieldIdx_f3 index, @b Field_f3 type and @b field_f3() access fuction
    ///         for @ref Msg1Fields::F3 field.
    ///     @li @b FieldIdx_f4 index, @b Field_f4 type and @b field_f4() access fuction
    ///         for @ref Msg1Fields::F4 field.
    COMMS_MSG_FIELDS_NAMES(
        f0,
        f1,
        f2,
        f3,
        f4
    );

    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static const std::size_t MsgMaxLen = Base::doMaxLength();
    static_assert(MsgMinLen == 4112U, "Unexpected min serialisation length");
    static_assert(MsgMaxLen == 4112U, "Unexpected max serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return adas::message::Msg1Common::name();
    }
};

} // namespace message

} // namespace adas
