// Generated by commsdsl2comms v6.3.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref adas::message::Msg1 message and its fields.

#pragma once

#include "adas/field/I0Common.h"
#include "adas/field/I1Common.h"
#include "adas/field/I2Common.h"
#include "adas/field/I3Common.h"
#include "adas/field/I4Common.h"

namespace adas
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref adas::message::Msg1 message.
/// @see adas::message::Msg1Fields
struct Msg1FieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref adas::message::Msg1Fields::F0 field.
    struct F0Common : public adas::field::I0Common
    {
        /// @brief Name of the @ref adas::message::Msg1Fields::F0 field.
        static const char* name()
        {
            return "F0";
        }
    };

    /// @brief Common types and functions for
    ///     @ref adas::message::Msg1Fields::F1 field.
    struct F1Common : public adas::field::I1Common
    {
        /// @brief Name of the @ref adas::message::Msg1Fields::F1 field.
        static const char* name()
        {
            return "F1";
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref adas::message::Msg1Fields::F2 field.
    using F2MembersCommon = adas::field::I2MembersCommon;

    /// @brief Common types and functions for
    ///     @ref adas::message::Msg1Fields::F2 field.
    struct F2Common : public adas::field::I2Common
    {
        /// @brief Name of the @ref adas::message::Msg1Fields::F2 field.
        static const char* name()
        {
            return "F2";
        }
    };

    /// @brief Common types and functions for
    ///     @ref adas::message::Msg1Fields::F3 field.
    struct F3Common : public adas::field::I3Common
    {
        /// @brief Name of the @ref adas::message::Msg1Fields::F3 field.
        static const char* name()
        {
            return "F3";
        }
    };

    /// @brief Common types and functions for
    ///     @ref adas::message::Msg1Fields::F4 field.
    struct F4Common : public adas::field::I4Common
    {
        /// @brief Name of the @ref adas::message::Msg1Fields::F4 field.
        static const char* name()
        {
            return "F4";
        }
    };
};

/// @brief Common types and functions of 
///     @ref adas::message::Msg1 message.
struct Msg1Common
{
    /// @brief Name of the @ref adas::message::Msg1 message.
    static const char* name()
    {
        return "Message 1";
    }
};

} // namespace message

} // namespace adas
